### PR TITLE
Memory model

### PR DESCRIPTION
**Pull request by andreiburdusa**
For the memory model:
- panic if a reading of more than 2^35 bytes is attempted
- (temporarely) exclude some tests

In addition to updating the memory model:
- fix `MSIZE`
- fix `aciveWords` count
- add `CALLCODE` and `STATICCALL`

### CODE REVIEW

**Review by Ferinko — CHANGES_REQUESTED** [review]
The only dangerous thing that stands out is that there are multiple places now where you 'compute' the max addresses from the number of active words (cf. `msize` and `copyMemory`) - is there a way to make it more difficult to not mess up and use the appropriate value ^^?

**Comment by andreiburdusa** [comment]
Now `activeWords` gets updated only in one writing function and one reading function.

**Review by Ferinko — CHANGES_REQUESTED** [review]
Can you please squish the WIP commits? Otherwise LGTM.

**Review by Ferinko — APPROVED** [review]
LGTM (`lake build` and `lake build conform` run locally too)

**Pull request merged**
